# Generated by Django 4.2 on 2023-06-01 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='studentid',
        ),
    ]
