# Generated by Django 4.2 on 2023-06-01 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_remove_student_studentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lastName',
        ),
    ]
